# Generated by Django 5.1.2 on 2024-10-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticcollection',
            name='collection_pic',
            field=models.ImageField(default='default.jpg', upload_to='plastic_collection/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
