# Generated by Django 5.1.2 on 2024-10-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plasticcollection_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasticcollection',
            name='status',
            field=models.CharField(choices=[('Request', 'Request'), ('Pending', 'Pending'), ('Collected', 'Collected')], default='Request', max_length=50),
        ),
    ]
