# Generated by Django 5.1.2 on 2024-10-28 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_badge_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentive',
            name='incentive_amount',
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='threshold_reached',
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='earned_incentives',
        ),
        migrations.AddField(
            model_name='incentive',
            name='points_required',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Visakhapatnam', 'Visakhapatnam'), ('Vijayawada', 'Vijayawada'), ('Guntur', 'Guntur'), ('Nellore', 'Nellore'), ('Itanagar', 'Itanagar'), ('Naharlagun', 'Naharlagun'), ('Guwahati', 'Guwahati'), ('Silchar', 'Silchar'), ('Dibrugarh', 'Dibrugarh'), ('Patna', 'Patna'), ('Gaya', 'Gaya'), ('Bhagalpur', 'Bhagalpur'), ('Raipur', 'Raipur'), ('Bhilai', 'Bhilai'), ('Bilaspur', 'Bilaspur'), ('Panaji', 'Panaji'), ('Margao', 'Margao'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Vadodara', 'Vadodara'), ('Rajkot', 'Rajkot'), ('Gurgaon', 'Gurgaon'), ('Faridabad', 'Faridabad'), ('Panipat', 'Panipat'), ('Shimla', 'Shimla'), ('Dharamshala', 'Dharamshala'), ('Ranchi', 'Ranchi'), ('Jamshedpur', 'Jamshedpur'), ('Dhanbad', 'Dhanbad'), ('Bengaluru', 'Bengaluru'), ('Mysuru', 'Mysuru'), ('Mangaluru', 'Mangaluru'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kochi', 'Kochi'), ('Kozhikode', 'Kozhikode'), ('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Gwalior', 'Gwalior'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Nashik', 'Nashik'), ('Imphal', 'Imphal'), ('Shillong', 'Shillong'), ('Aizawl', 'Aizawl'), ('Kohima', 'Kohima'), ('Dimapur', 'Dimapur'), ('Bhubaneswar', 'Bhubaneswar'), ('Cuttack', 'Cuttack'), ('Rourkela', 'Rourkela'), ('Chandigarh', 'Chandigarh'), ('Ludhiana', 'Ludhiana'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur'), ('Jodhpur', 'Jodhpur'), ('Udaipur', 'Udaipur'), ('Gangtok', 'Gangtok'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Hyderabad', 'Hyderabad'), ('Warangal', 'Warangal'), ('Agartala', 'Agartala'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Varanasi', 'Varanasi'), ('Dehradun', 'Dehradun'), ('Haridwar', 'Haridwar'), ('Kolkata', 'Kolkata'), ('Howrah', 'Howrah'), ('Durgapur', 'Durgapur'), ('Port Blair', 'Port Blair'), ('Chandigarh', 'Chandigarh'), ('Daman', 'Daman'), ('Silvassa', 'Silvassa'), ('Kavaratti', 'Kavaratti'), ('New Delhi', 'New Delhi'), ('Puducherry', 'Puducherry'), ('Leh', 'Leh'), ('Srinagar', 'Srinagar'), ('Jammu', 'Jammu')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earned_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry'), ('Ladakh', 'Ladakh'), ('Jammu and Kashmir', 'Jammu and Kashmir')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_plastic_recycled',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.incentive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
    ]
