# Generated by Django 5.1.2 on 2024-10-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_incentive_incentive_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incentive',
            new_name='ListReward',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='incentive',
            new_name='reward',
        ),
    ]
