# Generated by Django 5.1.2 on 2024-10-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_listreward_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='assigned_date',
            new_name='claimed_date',
        ),
    ]
