# Generated by Django 5.1.2 on 2024-10-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_assigned_date_reward_claimed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='main.userprofile'),
        ),
    ]
