id: build-docker-images
namespace: company.team

tasks:
  - id: build-backend
    type: io.kestra.plugin.docker.build
    dockerfile: |
      FROM python:3

      RUN pip install --upgrade pip

      COPY ../../backend/requirements.txt .
      RUN pip install -r requirements.txt

      COPY ../../backend /app

      WORKDIR /app

      COPY ../../backend/entrypoint.sh /
      ENTRYPOINT ["sh", "/entrypoint.sh"]
    tags:
      - xonoxc/cygree_backend:latest
    push: true
    credentials:
      registry: https://index.docker.io/v1/
      username: "{{ secret('dockerhub_username') }}"
      password: "{{ secret('dockerhub_password') }}"

  - id: build-frontend
    type: io.kestra.plugin.docker.build
    dockerfile: |
      FROM node:16-alpine

      RUN curl -fsSL https://bun.sh/install | bash

      ENV PATH="/root/.bun/bin:$PATH"

      COPY ../../frontend/package.json ../../frontend/bun.lockb /app/
      WORKDIR /app
      RUN bun install

      COPY ../../frontend /app
      RUN bun build

      CMD ["bun", "start"]
    tags:
      - xonoxc/cygree_frontend:latest
    push: true
    credentials:
      registry: https://index.docker.io/v1/
      username: "{{ secret('dockerhub_username') }}"
      password: "{{ secret('dockerhub_password') }}"
